"""initial schema

Revision ID: 0002_initial_schema
Revises: 0001_baseline
Create Date: 2026-10-07 07:03:10.465050

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate may emit sqlmodel types)
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_initial_schema"
down_revision: str | Sequence[str] | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_table(
        "regulatory_agency",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scheme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data_mode", sa.String(length=4), nullable=False),
        sa.CheckConstraint("data_mode IN ('DEMO')", name=op.f("ck_regulatory_agency_data_mode")),
        sa.PrimaryKeyConstraint("agency_id", name=op.f("pk_regulatory_agency")),
        sa.UniqueConstraint("name", "scheme", name=op.f("uq_regulatory_agency_name_scheme")),
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_audit_log_actor_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("audit_id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_entity_type"), "audit_log", ["entity_type"], unique=False)
    op.create_table(
        "company",
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_type", sa.String(length=12), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("claimed_legal_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("claimed_business_identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("claimed_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("review_status", sa.String(length=14), nullable=False),
        sa.CheckConstraint(
            "company_type IN ('MANUFACTURER', 'WHOLESALER', 'BOTH')",
            name=op.f("ck_company_company_type"),
        ),
        sa.CheckConstraint(
            "review_status IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED')",
            name=op.f("ck_company_review_status"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_company_reviewed_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("company_id", name=op.f("pk_company")),
    )
    op.create_table(
        "user_session",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.user_id"], name=op.f("fk_user_session_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_user_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_session_token_hash")),
    )
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    op.create_table(
        "company_member",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=14), nullable=False),
        sa.Column("membership_status", sa.String(length=8), nullable=False),
        sa.Column("is_public_contact", sa.Boolean(), nullable=False),
        sa.Column("public_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("public_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("public_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "membership_status IN ('ACTIVE', 'INACTIVE')",
            name=op.f("ck_company_member_membership_status"),
        ),
        sa.CheckConstraint(
            "role IN ('OWNER', 'REPRESENTATIVE')", name=op.f("ck_company_member_member_role")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.company_id"],
            name=op.f("fk_company_member_company_id_company"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.user_id"], name=op.f("fk_company_member_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("member_id", name=op.f("pk_company_member")),
        sa.UniqueConstraint("user_id", name=op.f("uq_company_member_user_id")),
    )
    op.create_index(
        op.f("ix_company_member_company_id"), "company_member", ["company_id"], unique=False
    )
    op.create_table(
        "product",
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("package_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("manufacturer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label_information", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=14), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'WITHDRAWN')",
            name=op.f("ck_product_product_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.company_id"], name=op.f("fk_product_company_id_company")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_product_reviewed_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_product")),
        sa.UniqueConstraint("product_code", name=op.f("uq_product_product_code")),
    )
    op.create_index(op.f("ix_product_company_id"), "product", ["company_id"], unique=False)
    op.create_table(
        "credential_record",
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("reference_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("data_mode", sa.String(length=4), nullable=False),
        sa.Column("provenance", sa.Text(), nullable=False),
        sa.Column("checked_on", sa.Date(), nullable=False),
        sa.Column("submitted_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("review_status", sa.String(length=14), nullable=False),
        sa.CheckConstraint("data_mode IN ('DEMO')", name=op.f("ck_credential_record_data_mode")),
        sa.CheckConstraint(
            "review_status IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED')",
            name=op.f("ck_credential_record_review_status"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'INACTIVE')", name=op.f("ck_credential_record_credential_status")
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from",
            name=op.f("ck_credential_record_valid_until_after_from"),
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["regulatory_agency.agency_id"],
            name=op.f("fk_credential_record_agency_id_regulatory_agency"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.product_id"],
            name=op.f("fk_credential_record_product_id_product"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_credential_record_reviewed_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_credential_record_submitted_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("credential_id", name=op.f("pk_credential_record")),
        sa.UniqueConstraint(
            "agency_id",
            "reference_number",
            name=op.f("uq_credential_record_agency_id_reference_number"),
        ),
    )
    op.create_index(
        op.f("ix_credential_record_agency_id"), "credential_record", ["agency_id"], unique=False
    )
    op.create_index(
        op.f("ix_credential_record_product_id"), "credential_record", ["product_id"], unique=False
    )
    op.create_table(
        "product_announcement",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("announcement_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("image_storage_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.String(length=6), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("hidden_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('LIVE', 'HIDDEN')", name=op.f("ck_product_announcement_announcement_status")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_product_announcement_created_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["hidden_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_product_announcement_hidden_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.product_id"],
            name=op.f("fk_product_announcement_product_id_product"),
        ),
        sa.PrimaryKeyConstraint("announcement_id", name=op.f("pk_product_announcement")),
    )
    op.create_index(
        op.f("ix_product_announcement_product_id"),
        "product_announcement",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_batch",
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("batch_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("production_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("qr_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("review_status", sa.String(length=14), nullable=False),
        sa.CheckConstraint(
            "review_status IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED')",
            name=op.f("ck_product_batch_review_status"),
        ),
        sa.CheckConstraint(
            "expiry_date IS NULL OR production_date IS NULL OR expiry_date >= production_date",
            name=op.f("ck_product_batch_expiry_after_production"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.product_id"], name=op.f("fk_product_batch_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_product_batch_reviewed_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("batch_id", name=op.f("pk_product_batch")),
        sa.UniqueConstraint(
            "product_id", "batch_number", name=op.f("uq_product_batch_product_id_batch_number")
        ),
        sa.UniqueConstraint("qr_token", name=op.f("uq_product_batch_qr_token")),
    )
    op.create_index(
        op.f("ix_product_batch_product_id"), "product_batch", ["product_id"], unique=False
    )
    op.create_table(
        "supplier_location",
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("area", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_member_id", sa.Uuid(), nullable=True),
        sa.Column("review_status", sa.String(length=14), nullable=False),
        sa.CheckConstraint(
            "review_status IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED')",
            name=op.f("ck_supplier_location_review_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.company_id"],
            name=op.f("fk_supplier_location_company_id_company"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_member_id"],
            ["company_member.member_id"],
            name=op.f("fk_supplier_location_contact_member_id_company_member"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_supplier_location_reviewed_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("location_id", name=op.f("pk_supplier_location")),
    )
    op.create_index(
        op.f("ix_supplier_location_company_id"), "supplier_location", ["company_id"], unique=False
    )
    op.create_table(
        "change_notice",
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notice_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("change_type", sa.String(length=18), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("submitted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("review_status", sa.String(length=23), nullable=False),
        sa.CheckConstraint(
            "change_type IN ('PACKAGING', 'LABEL', 'PRODUCT_DETAILS', 'BATCH_DETAILS', 'CREDENTIAL_DETAILS', 'LOCATION_DETAILS', 'OTHER')",
            name=op.f("ck_change_notice_change_type"),
        ),
        sa.CheckConstraint(
            "review_status IN ('PENDING_REVIEW', 'CLARIFICATION_REQUESTED', 'APPROVED', 'REJECTED')",
            name=op.f("ck_change_notice_change_notice_status"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(product_id, batch_id, credential_id, location_id) = 1",
            name=op.f("ck_change_notice_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["product_batch.batch_id"],
            name=op.f("fk_change_notice_batch_id_product_batch"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.company_id"], name=op.f("fk_change_notice_company_id_company")
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credential_record.credential_id"],
            name=op.f("fk_change_notice_credential_id_credential_record"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["supplier_location.location_id"],
            name=op.f("fk_change_notice_location_id_supplier_location"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.product_id"], name=op.f("fk_change_notice_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_change_notice_reviewed_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_change_notice_submitted_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("notice_id", name=op.f("pk_change_notice")),
    )
    op.create_index(
        op.f("ix_change_notice_company_id"), "change_notice", ["company_id"], unique=False
    )
    op.create_table(
        "wholesale_order",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_company_id", sa.Uuid(), nullable=False),
        sa.Column("seller_company_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("pickup_location_id", sa.Uuid(), nullable=True),
        sa.Column("fulfilment_method", sa.String(length=8), nullable=False),
        sa.Column("delivery_details", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=9), nullable=False),
        sa.Column("buyer_note", sa.Text(), nullable=True),
        sa.Column("seller_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "fulfilment_method IN ('PICKUP', 'DELIVERY')",
            name=op.f("ck_wholesale_order_fulfilment_method"),
        ),
        sa.CheckConstraint(
            "status IN ('SUBMITTED', 'ACCEPTED', 'DECLINED', 'FULFILLED', 'CANCELLED')",
            name=op.f("ck_wholesale_order_order_status"),
        ),
        sa.CheckConstraint(
            "buyer_company_id <> seller_company_id",
            name=op.f("ck_wholesale_order_buyer_not_seller"),
        ),
        sa.ForeignKeyConstraint(
            ["buyer_company_id"],
            ["company.company_id"],
            name=op.f("fk_wholesale_order_buyer_company_id_company"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_wholesale_order_created_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["pickup_location_id"],
            ["supplier_location.location_id"],
            name=op.f("fk_wholesale_order_pickup_location_id_supplier_location"),
        ),
        sa.ForeignKeyConstraint(
            ["seller_company_id"],
            ["company.company_id"],
            name=op.f("fk_wholesale_order_seller_company_id_company"),
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_wholesale_order")),
    )
    op.create_index(
        op.f("ix_wholesale_order_buyer_company_id"),
        "wholesale_order",
        ["buyer_company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wholesale_order_seller_company_id"),
        "wholesale_order",
        ["seller_company_id"],
        unique=False,
    )
    op.create_table(
        "change_notice_field",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("field_change_id", sa.Uuid(), nullable=False),
        sa.Column("notice_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_value", sa.Text(), nullable=True),
        sa.Column("proposed_value", sa.Text(), nullable=True),
        sa.Column("applied_old_value", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["change_notice.notice_id"],
            name=op.f("fk_change_notice_field_notice_id_change_notice"),
        ),
        sa.PrimaryKeyConstraint("field_change_id", name=op.f("pk_change_notice_field")),
        sa.UniqueConstraint(
            "notice_id", "field_name", name=op.f("uq_change_notice_field_notice_id_field_name")
        ),
    )
    op.create_index(
        op.f("ix_change_notice_field_notice_id"), "change_notice_field", ["notice_id"], unique=False
    )
    op.create_table(
        "notice_attachment",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("attachment_id", sa.Uuid(), nullable=False),
        sa.Column("notice_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime_type", sa.String(length=15), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "mime_type IN ('application/pdf', 'image/png', 'image/jpeg')",
            name=op.f("ck_notice_attachment_attachment_mime_type"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 5242880", name=op.f("ck_notice_attachment_size_limit")
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["change_notice.notice_id"],
            name=op.f("fk_notice_attachment_notice_id_change_notice"),
        ),
        sa.PrimaryKeyConstraint("attachment_id", name=op.f("pk_notice_attachment")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_notice_attachment_storage_key")),
    )
    op.create_index(
        op.f("ix_notice_attachment_notice_id"), "notice_attachment", ["notice_id"], unique=False
    )
    op.create_table(
        "order_line",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_line_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["wholesale_order.order_id"],
            name=op.f("fk_order_line_order_id_wholesale_order"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.product_id"], name=op.f("fk_order_line_product_id_product")
        ),
        sa.PrimaryKeyConstraint("line_id", name=op.f("pk_order_line")),
    )
    op.create_index(op.f("ix_order_line_order_id"), "order_line", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_line_product_id"), "order_line", ["product_id"], unique=False)
    op.create_table(
        "order_batch_allocation",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("allocated_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.CheckConstraint(
            "allocated_quantity > 0",
            name=op.f("ck_order_batch_allocation_allocated_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["product_batch.batch_id"],
            name=op.f("fk_order_batch_allocation_batch_id_product_batch"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["order_line.line_id"],
            name=op.f("fk_order_batch_allocation_line_id_order_line"),
        ),
        sa.PrimaryKeyConstraint("allocation_id", name=op.f("pk_order_batch_allocation")),
    )
    op.create_index(
        op.f("ix_order_batch_allocation_batch_id"),
        "order_batch_allocation",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_batch_allocation_line_id"),
        "order_batch_allocation",
        ["line_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_batch_allocation_line_id"), table_name="order_batch_allocation")
    op.drop_index(op.f("ix_order_batch_allocation_batch_id"), table_name="order_batch_allocation")
    op.drop_table("order_batch_allocation")
    op.drop_index(op.f("ix_order_line_product_id"), table_name="order_line")
    op.drop_index(op.f("ix_order_line_order_id"), table_name="order_line")
    op.drop_table("order_line")
    op.drop_index(op.f("ix_notice_attachment_notice_id"), table_name="notice_attachment")
    op.drop_table("notice_attachment")
    op.drop_index(op.f("ix_change_notice_field_notice_id"), table_name="change_notice_field")
    op.drop_table("change_notice_field")
    op.drop_index(op.f("ix_wholesale_order_seller_company_id"), table_name="wholesale_order")
    op.drop_index(op.f("ix_wholesale_order_buyer_company_id"), table_name="wholesale_order")
    op.drop_table("wholesale_order")
    op.drop_index(op.f("ix_change_notice_company_id"), table_name="change_notice")
    op.drop_table("change_notice")
    op.drop_index(op.f("ix_supplier_location_company_id"), table_name="supplier_location")
    op.drop_table("supplier_location")
    op.drop_index(op.f("ix_product_batch_product_id"), table_name="product_batch")
    op.drop_table("product_batch")
    op.drop_index(op.f("ix_product_announcement_product_id"), table_name="product_announcement")
    op.drop_table("product_announcement")
    op.drop_index(op.f("ix_credential_record_product_id"), table_name="credential_record")
    op.drop_index(op.f("ix_credential_record_agency_id"), table_name="credential_record")
    op.drop_table("credential_record")
    op.drop_index(op.f("ix_product_company_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_company_member_company_id"), table_name="company_member")
    op.drop_table("company_member")
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_table("company")
    op.drop_index(op.f("ix_audit_log_entity_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("regulatory_agency")
    op.drop_table("app_user")
    # ### end Alembic commands ###
