"""batch scan log

Revision ID: 0003_batch_scan
Revises: 0002_initial_schema
Create Date: 2026-10-08 16:12:34.606548

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate may emit sqlmodel types)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_batch_scan"
down_revision: str | Sequence[str] | None = "0002_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_scan",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("input_product_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("input_batch_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("matched_batch_id", sa.Uuid(), nullable=True),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.CheckConstraint(
            "result IN ('DEMO_RECORD_FOUND', 'BATCH_NOT_FOUND', 'BATCH_EXPIRED', 'DETAILS_MISMATCH', 'CREDENTIAL_EXPIRED_OR_INACTIVE', 'INSUFFICIENT_OR_AMBIGUOUS')",
            name=op.f("ck_batch_scan_lookup_result"),
        ),
        sa.ForeignKeyConstraint(
            ["matched_batch_id"],
            ["product_batch.batch_id"],
            name=op.f("fk_batch_scan_matched_batch_id_product_batch"),
        ),
        sa.PrimaryKeyConstraint("scan_id", name=op.f("pk_batch_scan")),
    )
    op.create_index(
        op.f("ix_batch_scan_matched_batch_id"), "batch_scan", ["matched_batch_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_batch_scan_matched_batch_id"), table_name="batch_scan")
    op.drop_table("batch_scan")
    # ### end Alembic commands ###
